import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthWrapper from "@/components/auth-wrapper"; // ✅ Nieuwe component voor client-side auth check
import { Toaster } from "@/components/ui/sonner"; // ✅ Sonner importeren

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthWrapper>{children}</AuthWrapper> {/* ✅ Auth check gebeurt nu in een aparte Client Component */}
        <Toaster richColors position="top-right" /> {/* ✅ Toaster toevoegen */}
      </body>
    </html>
  );
}